[versions]
cfr = "0.152"
teavm = "0.16.0-dev-5"
junit = "6.1.0"

[libraries]
cfr = { group = "org.benf", name = "cfr", version.ref = "cfr" }
teavm-extension-annotation-processor = { group = "org.teavm", name = "teavm-extension-annotation-processor", version.ref = "teavm" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }

[plugins]
teavm = { id = "org.teavm", version.ref = "teavm" }
